### ISSUE TITLE
ks-demo-pod.yaml - formatting needs to be looked at.

### ISSUE THREAD

**Issue by garridor76** [linuxacademy/content-kubernetes-security#1]
There is an issue with the formatting of a YAML file referenced in AuthN video.

As Is:
```
apiVersion: v1
kind: Pod
metadata:
  name: ks-demo-pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: shell
    image: alpine:3.7
	command:
	- "sh"
	- "-c"
	- "sleep 10000"
```

Should be:
```
apiVersion: v1
kind: Pod
metadata:
  name: ks-demo-pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: shell
    image: alpine:3.7
    command:
    - "sh"
    - "-c"
    - "sleep 10000"
```

Troubleshooting/error messages:
```
cloud_user@garridor1c ~]$ kubectl apply -f ks-demo-pod.yaml
error: error parsing ks-demo-pod.yaml: error converting YAML to JSON: yaml: line 10: found a tab character that violates indentation
[cloud_user@garridor1c ~]$ vim ks-demo-pod.yaml
[cloud_user@garridor1c ~]$ kubectl apply -f ks-demo-pod.yaml
pod/ks-demo-pod created
```
